# Generated by Django 4.1.1 on 2022-10-22 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400, null=True)),
                ('desc', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category', models.CharField(max_length=200, null=True)),
                ('marks', models.IntegerField(default=0)),
                ('op1', models.CharField(max_length=200, null=True)),
                ('op2', models.CharField(max_length=200, null=True)),
                ('op3', models.CharField(max_length=200, null=True)),
                ('op4', models.CharField(max_length=200, null=True)),
                ('ans', models.CharField(max_length=200, null=True)),
                ('explaination', models.CharField(default='', max_length=400, null=True)),
                ('subject', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, max_length=30, null=True)),
                ('last_name', models.TextField(blank=True, max_length=30, null=True)),
                ('email', models.TextField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, max_length=400, null=True)),
                ('profileimg', models.ImageField(default='https://cdn5.vectorstock.com/i/thumb-large/45/59/profile-photo-placeholder-icon-design-in-gray-vector-37114559.jpg', upload_to='profile_images')),
                ('location', models.CharField(blank=True, max_length=400, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
