# Generated by Django 4.1.1 on 2022-10-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='default-profile-img.jpg', upload_to='profile_images/'),
        ),
    ]
